# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

env:
  IMAGE_ID: "xcode-26.0"

steps:
  - label: "🕵️ Lint"
    agents:
      queue: default
    command: |
      .buildkite/install_rust.sh
      .buildkite/lint.sh

  - group: "🔬 Test"
    steps:
      - label: "🔬 Test macOS"
        key: check-macos
        agents:
          queue: mac
        command: |
          .buildkite/install_rust.sh
          .buildkite/test.sh

      - label: "🔬 Test Linux"
        key: check-linux
        agents:
          queue: default
        command: |
          .buildkite/install_rust.sh
          .buildkite/test.sh

      - label: "🔬 Test Windows"
        key: check-windows
        agents:
          queue: windows
        command: |
          bash .buildkite/test.sh

  - group: "Build"
    if: build.branch == 'trunk' || build.tag != null
    steps:
      - label: "Build macOS"
        key: build-macos
        depends_on: check-macos
        agents:
          queue: mac
        command: |
          .buildkite/install_rust.sh
          .buildkite/build_and_upload_artifact.sh

      - label: "Build Linux"
        key: build-linux
        depends_on: check-linux
        agents:
          queue: default
        command: |
          .buildkite/install_rust.sh
          .buildkite/build_and_upload_artifact.sh

      - label: "Build Windows"
        key: build-windows
        depends_on: check-windows
        agents:
          queue: windows
        command: |
          bash .buildkite/build_and_upload_artifact.sh .exe

  - label: "Create GitHub Release"
    if: build.tag != null
    depends_on: [build-macos, build-linux, build-windows]
    agents:
      queue: default
    command: .buildkite/create_github_release.sh
