# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

env:
  IMAGE_ID: "xcode-26.0"

steps:
  - group: "Build"
    steps:
      - label: "Build macOS"
        key: build-macos
        agents:
          queue: mac
        command: |
          echo "~~~ Installing Rust via Homebrew..."
          brew install rust

          .buildkite/build_and_upload_artifact.sh

      - label: "Build Linux"
        key: build-linux
        agents:
          queue: default
        command: |
          echo "~~~ Installing Rust via rustup..."
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

          .buildkite/build_and_upload_artifact.sh

      - label: "Build Windows"
        key: build-windows
        agents:
          queue: windows
        command: |
          bash .buildkite/build_and_upload_artifact.sh .exe
  - group: "Test"
    steps:
      - label: "Test macOS"
        depends_on: build-macos
        agents:
          queue: mac
        command: |
          .buildkite/test_decrypt.sh aarch64-apple-darwin

      - label: "Test Linux"
        depends_on: build-linux
        agents:
          queue: default
        command: |
          .buildkite/test_decrypt.sh x86_64-unknown-linux-gnu

      - label: "Test windows"
        depends_on: build-windows
        agents:
          queue: windows
        command: |
          bash .buildkite/test_decrypt.sh x86_64-pc-windows-gnu
