# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---
steps:
  - label: "Build macOS"
    agents:
      queue: mac
    env:
      IMAGE_ID: "xcode-26.0"
    command: |
      echo "~~~ Installing Rust via Homebrew..."
      brew install rust

      .buildkite/build_and_upload_artifact.sh

  - label: "Build Linux"
    agents:
      queue: default
    command: |
      echo "~~~ Installing Rust via rustup..."
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      .buildkite/build_and_upload_artifact.sh

  - label: "Build Windows"
    agents:
      queue: windows
    command: |
      bash .buildkite/build_and_upload_artifact.sh .exe
